import {describe,expect,it,vi,beforeEach} from 'vitest';
import {api,getAccessToken,setAccessToken,registerClearAuth} from './http';
describe('auth HTTP foundation',()=>{
 beforeEach(()=>{setAccessToken(null);api.defaults.adapter=undefined as never;});
 it('keeps access token in memory only',()=>{setAccessToken('secret');expect(getAccessToken()).toBe('secret');if(typeof localStorage!=='undefined')expect(localStorage.getItem('accessToken')).toBeNull();if(typeof sessionStorage!=='undefined')expect(sessionStorage.getItem('accessToken')).toBeNull();});
 it('adds bearer and csrf headers to state-changing calls',async()=>{setAccessToken('token');let seen:any;api.defaults.adapter=async config=>{seen=config;return {data:{},status:200,statusText:'OK',headers:{},config}};document.cookie='XSRF-TOKEN=csrf-value';await api.post('/auth/logout',{});expect(seen.headers.Authorization).toBe('Bearer token');expect(seen.headers['X-XSRF-TOKEN']).toBe('csrf-value');});
 it('shares refresh and retries a 401 once',async()=>{setAccessToken('old');let calls=0,refreshes=0;api.defaults.adapter=async config=>{if(config.url==='/auth/refresh'){refreshes++;return {data:{accessToken:'new'},status:200,statusText:'OK',headers:{},config}}calls++;if(calls===1)return Promise.reject({config,response:{status:401}});return {data:{ok:true},status:200,statusText:'OK',headers:{},config}};const [a,b]=await Promise.all([api.get('/data'),api.get('/data')]);expect(a.data.ok).toBe(true);expect(b.data.ok).toBe(true);expect(refreshes).toBe(1);});
 it('clears memory state when refresh fails',async()=>{let cleared=0;registerClearAuth(()=>cleared++);api.defaults.adapter=async config=>config.url==='/auth/refresh'?Promise.reject({config,response:{status:401}}):Promise.reject({config,response:{status:401}});await expect(api.get('/data')).rejects.toBeTruthy();expect(cleared).toBe(1);expect(getAccessToken()).toBeNull();});
});
