package fr.afpa.gestioneleves.enumtype;

public enum SecurityEventType {
    INVITATION_CREATED,
    INVITATION_RESENT,
    ACTIVATION_USED,
    ACTIVATION_REVOKED,
    ACTIVATION_EXPIRED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_USED,
    PASSWORD_RESET_REVOKED,
    REFRESH_FAMILY_REVOKED,
    REFRESH_TOKEN_REUSE_DETECTED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_REACTIVATED,
    EMAIL_DELIVERY_ATTEMPT,
    EMAIL_DELIVERY_SUCCEEDED,
    EMAIL_DELIVERY_FAILED
}
