package fr.afpa.gestioneleves.integration;

import fr.afpa.gestioneleves.entity.*;
import fr.afpa.gestioneleves.enumtype.*;
import fr.afpa.gestioneleves.repository.*;
import fr.afpa.gestioneleves.dto.request.BulletinGenerateRequest;
import fr.afpa.gestioneleves.service.BulletinService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.security.oauth2.jwt.*;
import org.springframework.security.oauth2.jose.jws.MacAlgorithm;
import fr.afpa.gestioneleves.security.AuthenticatedUser;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import java.math.BigDecimal; import java.time.*;
import java.util.UUID;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Testcontainers @Transactional
class BulletinVersionIntegrationTest {
 @Container static final PostgreSQLContainer<?> DB=new PostgreSQLContainer<>("postgres:15-alpine").withDatabaseName("bulletin_versions").withUsername("test").withPassword("test");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",DB::getJdbcUrl);r.add("spring.datasource.username",DB::getUsername);r.add("spring.datasource.password",DB::getPassword);}
 @Autowired BulletinRepository bulletins; @Autowired EleveRepository eleves; @Autowired ClasseRepository classes; @Autowired InscriptionRepository inscriptions; @Autowired EnseignantRepository enseignants; @Autowired MatiereRepository matieres; @Autowired EnseignementRepository enseignements; @Autowired NoteRepository notes; @Autowired BulletinService bulletinService; @Autowired MockMvc mvc; @Autowired JwtEncoder encoder; @Autowired UtilisateurRepository users; @Autowired ResponsableRepository guardians; @Autowired EleveResponsableRepository links;
 @Test void v6AllowsHistoryButOnlyOnePublishedCurrentVersion(){ Eleve e=new Eleve();e.setNumeroDossier("BV");e.setNom("B");e.setPrenom("V");e.setDateNaissance(LocalDate.now().minusYears(12));eleves.save(e); Classe c=new Classe();c.setCode("BV");c.setNom("BV");c.setNiveau("6e");c.setAnneeScolaire("2025-2026");classes.save(c); Inscription i=new Inscription();i.setEleve(e);i.setClasse(c);i.setAnneeScolaire(c.getAnneeScolaire());i.setDateInscription(LocalDate.now());i.setStatut(StatutInscription.EN_COURS);inscriptions.save(i); Bulletin old=b(i,StatutBulletin.REMPLACE); Bulletin current=b(i,StatutBulletin.PUBLIE); bulletins.saveAndFlush(old);bulletins.saveAndFlush(current); assertThat(bulletins.findByInscriptionIdOrderByDateGenerationDesc(i.getId())).hasSize(2); Bulletin duplicate=b(i,StatutBulletin.PUBLIE); assertThatThrownBy(()->bulletins.saveAndFlush(duplicate)).isInstanceOf(Exception.class); }
 @Test void publishedSnapshotRemainsStoredWhenSourceNotesChange(){ Eleve e=eleve("SN"); Classe c=classe("SN"); Inscription i=registration(e,c); Enseignant teacher=new Enseignant();teacher.setMatricule("SN");teacher.setNom("N");teacher.setPrenom("T");teacher.setEmail("sn@x.fr");enseignants.save(teacher); Matiere subject=new Matiere();subject.setCode("SN");subject.setNom("Snapshot");subject.setCoefficientDefaut(BigDecimal.ONE);subject.setActif(true);matieres.save(subject); Enseignement teaching=new Enseignement();teaching.setEnseignant(teacher);teaching.setMatiere(subject);teaching.setClasse(c);teaching.setAnneeScolaire(c.getAnneeScolaire());teaching.setCoefficientMatiere(BigDecimal.ONE);enseignements.save(teaching); Note note=new Note();note.setInscription(i);note.setEnseignement(teaching);note.setPeriode(PeriodeBulletin.TRIMESTRE_1);note.setValeur(new BigDecimal("12"));note.setBareme(new BigDecimal("20"));note.setCoefficient(BigDecimal.ONE);note.setDateEvaluation(LocalDate.now());note.setLibelle("Évaluation");notes.saveAndFlush(note); Long id=bulletinService.generer(new BulletinGenerateRequest(i.getId(),PeriodeBulletin.TRIMESTRE_1,"Bien")).id();bulletinService.publier(id); Bulletin before=bulletins.findById(id).orElseThrow();BigDecimal average=before.getMoyenneGenerale();BigDecimal line=before.getLignes().getFirst().getMoyenne();note.setValeur(new BigDecimal("18"));notes.saveAndFlush(note); Bulletin after=bulletins.findById(id).orElseThrow();assertThat(after.getMoyenneGenerale()).isEqualByComparingTo(average);assertThat(after.getLignes()).hasSize(1);assertThat(after.getLignes().getFirst().getMoyenne()).isEqualByComparingTo(line); }
@Test void publishedPdfIsVisibleOnlyToAuthorizedCurrentActors() throws Exception { Eleve e=eleve("PV");Classe c=classe("PV");Inscription i=registration(e,c); Bulletin published=b(i,StatutBulletin.PUBLIE);BulletinLigne line=new BulletinLigne();line.setCodeMatiere("PV");line.setNomMatiere("PDF");line.setMoyenne(BigDecimal.TEN);line.setCoefficient(BigDecimal.ONE);line.setNombreNotes(1);published.ajouterLigne(line);published=bulletins.saveAndFlush(published); Utilisateur gu=user("g",Role.RESPONSABLE);Responsable guardian=guardian("g",gu);EleveResponsable link=new EleveResponsable();link.setEleve(e);link.setResponsable(guardian);link.setLienParente(LienParente.PERE);link.setValidFrom(LocalDate.now());links.saveAndFlush(link); Utilisateur ta=user("ta",Role.ENSEIGNANT);Enseignant teacher=teacher("ta",ta);Enseignement teaching=new Enseignement();teaching.setEnseignant(teacher);teaching.setClasse(c);Matiere m=new Matiere();m.setCode("PV");m.setNom("PV");m.setCoefficientDefaut(BigDecimal.ONE);m.setActif(true);teaching.setMatiere(matieres.saveAndFlush(m));teaching.setAnneeScolaire(c.getAnneeScolaire());teaching.setCoefficientMatiere(BigDecimal.ONE);enseignements.saveAndFlush(teaching); Utilisateur tb=user("tb",Role.ENSEIGNANT);teacher("tb",tb); mvc.perform(get("/api/bulletins/{id}/pdf",published.getId()).header("Authorization",bearer(gu))).andExpect(status().isOk()).andExpect(content().contentType("application/pdf")).andExpect(result -> assertThat(result.getResponse().getContentAsByteArray()).isNotEmpty()); mvc.perform(get("/api/bulletins/{id}/pdf",published.getId()).header("Authorization",bearer(ta))).andExpect(status().isOk()); mvc.perform(get("/api/bulletins/{id}/pdf",published.getId()).header("Authorization",bearer(tb))).andExpect(status().isNotFound()); link.setValidTo(LocalDate.now());links.saveAndFlush(link);mvc.perform(get("/api/bulletins/{id}/pdf",published.getId()).header("Authorization",bearer(gu))).andExpect(status().isNotFound()); }
 private Bulletin b(Inscription i,StatutBulletin s){Bulletin b=new Bulletin();b.setInscription(i);b.setPeriode(PeriodeBulletin.TRIMESTRE_1);b.setDateGeneration(LocalDateTime.now());b.setStatut(s);b.setMoyenneGenerale(BigDecimal.TEN);return b;}
 private Eleve eleve(String n){Eleve e=new Eleve();e.setNumeroDossier(n);e.setNom(n);e.setPrenom(n);e.setDateNaissance(LocalDate.now().minusYears(12));return eleves.saveAndFlush(e);} private Classe classe(String n){Classe c=new Classe();c.setCode(n);c.setNom(n);c.setNiveau("6e");c.setAnneeScolaire("2025-2026");return classes.saveAndFlush(c);} private Inscription registration(Eleve e,Classe c){Inscription i=new Inscription();i.setEleve(e);i.setClasse(c);i.setAnneeScolaire(c.getAnneeScolaire());i.setDateInscription(LocalDate.now());i.setStatut(StatutInscription.EN_COURS);return inscriptions.saveAndFlush(i);}
 private Utilisateur user(String n,Role r){Utilisateur u=new Utilisateur();u.setEmailNormalise(n+"@x.fr");u.setRole(r);u.setStatut(StatutUtilisateur.ACTIF);u.setPasswordHash("x");u.setEmailVerifieAt(LocalDateTime.now());return users.saveAndFlush(u);} private Responsable guardian(String n,Utilisateur u){Responsable r=new Responsable();r.setNom(n);r.setPrenom(n);r.setEmail(n+"@x.fr");r.setUtilisateur(u);return guardians.saveAndFlush(r);} private Enseignant teacher(String n,Utilisateur u){Enseignant e=new Enseignant();e.setMatricule(n);e.setNom(n);e.setPrenom(n);e.setEmail(n+"@x.fr");e.setUtilisateur(u);return enseignants.saveAndFlush(e);} private String bearer(Utilisateur u){JwtClaimsSet c=JwtClaimsSet.builder().subject(u.getId().toString()).issuer("gestion-eleves-api-test").issuedAt(Instant.now()).expiresAt(Instant.now().plusSeconds(600)).id(UUID.randomUUID().toString()).claim("role",u.getRole().name()).claim("ver",u.getTokenVersion()).build();return "Bearer "+encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),c)).getTokenValue();}
}
