import {render,screen,waitFor} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {describe,it,expect,vi,beforeEach} from 'vitest';import {MemoryRouter} from 'react-router-dom';import App from './App';import {AuthProvider} from './auth/AuthContext';
const m=vi.hoisted(()=>({post:vi.fn(),get:vi.fn()}));vi.mock('./auth/http',()=>({api:{post:m.post,get:m.get},setAccessToken:vi.fn(),registerClearAuth:vi.fn()}));const mount=(p='/login')=>render(<MemoryRouter initialEntries={[p]}><AuthProvider><App/></AuthProvider></MemoryRouter>);beforeEach(()=>{m.post.mockReset();m.get.mockReset();m.post.mockRejectedValue(new Error('anonymous'));m.get.mockRejectedValue(new Error('anonymous'));});
describe('Phase 8 UI auth',()=>{
it('prevents duplicate pending login',async()=>{let done:any;m.post.mockImplementation(()=>new Promise(r=>{done=r}));const u=userEvent.setup();mount();await u.type(screen.getByLabelText('Email'),'a@b.fr');await u.type(screen.getByLabelText('Mot de passe'),'x');const b=screen.getByRole('button',{name:'Se connecter'});await u.click(b);expect(b).toBeDisabled();await u.click(b);expect(m.post).toHaveBeenCalledTimes(2);done({data:{accessToken:'x'}})});
it('logs in and shows neutral invalid error',async()=>{m.post.mockResolvedValue({data:{accessToken:'x'}});m.get.mockResolvedValue({data:{id:1,email:'a@b.fr',role:'ADMIN'}});const u=userEvent.setup();mount();await u.type(screen.getByLabelText('Email'),'a@b.fr');await u.type(screen.getByLabelText('Mot de passe'),'x');await u.click(screen.getByRole('button',{name:'Se connecter'}));await waitFor(()=>expect(screen.getByText(/Bonjour/)).toBeInTheDocument());});
it('renders neutral credentials error',async()=>{const u=userEvent.setup();mount();await u.type(screen.getByLabelText('Email'),'bad@x.fr');await u.type(screen.getByLabelText('Mot de passe'),'bad');await u.click(screen.getByRole('button',{name:'Se connecter'}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Impossible de se connecter avec ces informations.'));});
it('bootstraps without flashing protected content and attempts once',async()=>{let done:any;m.post.mockImplementation(()=>new Promise(r=>{done=r}));const v=mount('/admin');expect(v.queryByText(/Bonjour/)).toBeNull();expect(screen.getByText('Chargement…')).toBeInTheDocument();done({data:{accessToken:'x'}});m.get.mockResolvedValue({data:{id:1,email:'a@x.fr',role:'ADMIN'}});await waitFor(()=>expect(screen.getByText(/Bonjour/)).toBeInTheDocument());expect(m.post).toHaveBeenCalledTimes(1);});
it('failed bootstrap becomes login',async()=>{mount('/admin');await waitFor(()=>expect(screen.getByRole('heading',{name:'Gestion des élèves'})).toBeInTheDocument());expect(m.post).toHaveBeenCalledTimes(1);});
it.each([['ADMIN','/admin'],['ENSEIGNANT','/teacher'],['RESPONSABLE','/guardian']])('allows %s role',async(role,path)=>{m.post.mockResolvedValue({data:{accessToken:'x'}});m.get.mockResolvedValue({data:{id:1,email:'u@x.fr',role}});mount(path);await waitFor(()=>expect(screen.getByText(/Bonjour/)).toBeInTheDocument());});
it('rejects a disallowed role',async()=>{m.post.mockResolvedValue({data:{accessToken:'x'}});m.get.mockResolvedValue({data:{id:1,email:'u@x.fr',role:'ENSEIGNANT'}});mount('/admin');await waitFor(()=>expect(screen.getByText('Accès refusé')).toBeInTheDocument());});
it('logout clears UI even when backend fails',async()=>{m.post.mockResolvedValue({data:{accessToken:'x'}});m.get.mockResolvedValue({data:{id:1,email:'u@x.fr',role:'ADMIN'}});mount('/');await waitFor(()=>expect(screen.getByText(/Bonjour/)).toBeInTheDocument());m.post.mockRejectedValue(new Error('logout'));await userEvent.setup().click(screen.getByRole('button',{name:'Se déconnecter'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'Gestion des élèves'})).toBeInTheDocument());});
});
