spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    fr.afpa.gestioneleves: DEBUG

app:
  mail:
    sender: ${MAIL_SENDER:no-reply@gestion-eleves.local}
    activation-url: ${APP_MAIL_ACTIVATION_URL:http://localhost:5173/activation}
    reset-url: ${APP_MAIL_RESET_URL:http://localhost:5173/reinitialisation-mot-de-passe}
  security:
    refresh-cookie:
      secure: false
